name: FastAPI-Azure-Deploy
env:
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
on:
  push:
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE_NAME}}

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE_NAME}}
#  ci_pipeline:
#      runs-on: ubuntu-latest
#      steps:
#          - uses: actions/checkout@v1
#            with:
#              fetch-depth: 0
#
#          - name: Set up Python 3.9
#            uses: actions/setup-python@v1
#            with:
#                python-version: 3.9
#
#          - name: Install dependencies
#            run: |
#                python -m pip install --upgrade pip
#                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#          - name: Test
#            run: |
#              python -m pytest test.py
#
#  cd_pipeline:
#
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v2
#        - name: Install dependencies
#          run: |
#            python -m pip install --upgrade pip
#            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#        - name: Deploy to Heroku
#          run: |
#            git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
#            git push heroku HEAD:master -f